spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    template:
      exchange: my-exchange
      routing-key: my-routing-key
      default-receive-queue: my-queue
    virtual-host: /