server:
  port: 8080

spring:
  application:
    name: sample-drools
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.33.10:30306/sample-drools?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
