---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-prometheus
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sample-prometheus
    spec:
      containers:
        - name: sample-prometheus
          image: "10.38.2.12:1000/library/sample-prometheus:0.0.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10

---
kind: Service
apiVersion: v1
metadata:
  name: sample-prometheus
  labels:
    app: sample-prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: sample-prometheus
