spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
mybatis:
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    use-column-label: true
  type-aliases-package: com.coding.sample.quartz.entity
  mapper-locations: classpath:mapper/**/*.xml